### ISSUE TITLE
responseSentTime is undefined

### ISSUE THREAD

**Issue by hugomd** [hapijs/good-console#101]
Hey 👋

Thanks for continuing to maintain and support this project, I really appreciate it 🙏

I seem to be getting logs like this:
```
2018-01-24T16:24:08Z, [response] http://localhost:3000: get /route {} 200 (responseSentTime: undefinedms) (responseTime: 14ms)
```

Where `responseSentTime` is `undefinedms`...

This is occurring with these dependencies:
```
"good": "^8.0.0-rc1",
"good-console": "^7.0.0",
"good-squeeze": "^5.0.2"
"hapi": "^17.2.0"
```

Any ideas?

✌️

**Comment by arb** [comment]
@berzniz any thoughts here since you made this change?

**Comment by berzniz** [comment]
This was written and tested with hapi 16. I’ll test it with 17. There might have been a breaking change there

**Comment by berzniz** [comment]
Well, there was a breaking change in `good`, documented here: https://github.com/hapijs/good/issues/575
![image](https://user-images.githubusercontent.com/170214/35351878-f50e85e6-014a-11e8-8cce-de81ee8fbe02.png)

There are two options that I suggest:
1. Remove the `responseSentTime` from the logging
2. Only show `responseSentTime` if it exists and omit it otherwise

What do you think? I'll submit a PR for one of these

**Comment by arb** [comment]
I'm more leaning towards option 1. I removed it from good because it is no longer available. Continued support for old versions of good + hapi is not really in the cards.

@hugomd if you need this value with yoursetup, you could be able to write a simple Transform stream to possibly add it?

**Comment by hugomd** [comment]
@arb I don't need the `responseSentTime`, but was just thinking it would be good for backwards compatibility. However, if the general stance is to not remain compatible with old versions of Hapi/Good then option 1 works 👌
