### ISSUE TITLE
Accepting of PR to allow format updates?

### ISSUE THREAD

**Issue by lostthetrail** [hapijs/good-console#74]
Would a PR potentially be accepted if someone wanted to allow for the log formats to be overridden? The defaults would remain true, but the feature would allow you to add format overrides to the options.

Thoughts? @arb

**Comment by arb** [comment]
No I don't think so. With good 7, it's trivial to write to `process.stdout` so write your own transform stream and piping it to stdout would be your best bet. 

`good-console` is generally used internally and I'm not really looking to expand or change it's API; especially because of how easy it is to do yourself with good 7.

Thanks for your interest!

**Comment by lostthetrail** [comment]
@arb Would you consider re-locating the utils methods out of the internals and into the class to allow overriding? Or maybe clone them into a this._utils in the constructor to allow overriding?

The purpose is to allow me to reformat the messages without having to completely clone & own the module.

Thoughts?

**Comment by arb** [comment]
What is your end goal? The utility good console provides doesn't seem like it's enough to warrant inheritance and extension.

**Comment by lostthetrail** [comment]
I was trying to extend the good console to supply a different format of message in certain cases. But to your point, maybe I should just fork it.
